In [41]:
from itertools import permutations as perms
import numpy as np

In [53]:
a1=1; k1=np.array([1,1,1])/np.sqrt(3)
a2=1; k2=np.array([1,0,0])
a3=0; k3=-k2
a4=0; k4=-k3

In [54]:
class phi_tilde:    
    def __init__(self,k,alpha=0,l=0,m=0):
        self.k=k
        self.alpha=alpha
        self.l=l
        self.m=m

In [55]:
phi1 = phi_tilde(k1,alpha=1)
phi2 = phi_tilde(k2,alpha=1)
phi3 = phi_tilde(k3,alpha=1)
phi4 = phi_tilde(k4,alpha=0)

In [56]:
for ordered in perms([phi1,phi2,phi3,phi4]):
    q1=-ordered[0].k
    q2=-ordered[0].k-ordered[1].k
    q3=-ordered[0].k-ordered[1].k-ordered[2].k
    
    sequence = (ordered[0].alpha,ordered[1].alpha,\
                ordered[2].alpha,ordered[3].alpha)
    
    if sequence == (0,0,0,0): # AAAA
        print('AAAA')
    
    if sequence == (0,0,0,1): # AAAB
        print('AAAB')   
    
    if sequence == (0,0,1,1): # AABB
        print('AABB')  
        
    if sequence == (0,1,1,1): # ABBB
        print('ABBB') 
        print(q1,q2,q3)
        
    if sequence == (1,1,1,1): # BBBB
        print('BBBB')

ABBB
[-1  0  0] [-1.57735027 -0.57735027 -0.57735027] [-2.57735027 -0.57735027 -0.57735027]
ABBB
[-1  0  0] [-1.57735027 -0.57735027 -0.57735027] [-0.57735027 -0.57735027 -0.57735027]
ABBB
[-1  0  0] [-2  0  0] [-2.57735027 -0.57735027 -0.57735027]
ABBB
[-1  0  0] [-2  0  0] [-1  0  0]
ABBB
[-1  0  0] [0 0 0] [-0.57735027 -0.57735027 -0.57735027]
ABBB
[-1  0  0] [0 0 0] [-1  0  0]
